import type { GetStaticProps, Metadata } from "next";
import { Inter, Raleway } from "next/font/google";
import "./globals.css";

import { Navbar } from "@/components/Navbar";
import PageTransition from "@/components/PageTransition";
import { Toaster } from "@/components/ui/toaster";
import { GoogleAnalytics } from "@next/third-parties/google";

const raleway = Raleway({style: "normal", subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Code Zero",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <div className="flex flex-col w-full h-full z-40">
          <Navbar/>
          <PageTransition>
            {children}
          </PageTransition>
          <Toaster/>
        </div>
      </body>
      <GoogleAnalytics gaId="G-HM9PE6NPEH"/>
    </html>
  );
}
